%% 
% SUMMARY: Generates mxm synthetic image used as input for various
% experiments.
%
% Specifically, images are generated by first choosing a randomly positioned
% "foreground" square. The size of this square is a parameter
% ("fraction_fg") that is a fraction of the total image's area. Intensities
% of background pixels are drawn uniformly from [0,1]; whereas foreground
% pixels are drawn uniformly from [0,10].
%
% See paper for further details.
%

function img = synthetic_img_input(m, fraction_fg)
n=m*m;
fg_max_intensity = 10;
bg_max_intensity = 1;

% MAKE BACKGROUND
img = bg_max_intensity*rand(m,m);

% MAKE FOREGROUND
% Randomly choose top left corners of foreground square
img_i = randi(m);
img_j = randi(m);
length_fg_side = floor(m*sqrt(fraction_fg));

% Redraw foreground pixels
for i=1:length_fg_side
    for j=1:length_fg_side
        % Get index (after possibly wrapping around)
        ind_i = mod(img_i+i,m);
        if ind_i == 0
            ind_i = m;
        end
        ind_j = mod(img_j+j,m);
        if ind_j == 0
            ind_j = m;
        end
        
        img(ind_i, ind_j)=fg_max_intensity*rand;
    end
end
% figure
% imshow(img)